### ISSUE TITLE
Internal types are not checked by IoT.js

### ISSUE THREAD

**Issue by zherczeg** [Samsung/iotjs#816] opened 2017-05-05 10:01 UTC
This is currently crashing:

    var Buffer = require('buffer');

    var buf = new Buffer("ABCDEF");

    var o = { _builtin: { compare:buf._builtin.compare }, compare: buf.compare };
    o.compare(buf);

We are creating a _builtin object which is a normal object, and this object has no internal property. It is even more dangerous if we use an object created by another module (and has an internal property to a different type).

Question: do we want to do something with it, or this is a misuse of the API?

**Comment by LaszloLango** [comment] 2017-05-05 11:39
I think this is bug. The internal objects must be hidden. `_onNextTick` and `_onUncaughtException` also available in the global object. This might caused by #748.

FYI, sample code to find internal objects:
```javascript
var keys = Object.keys(global);

for(var i=0; i < keys.length; i++)
{
  var str = /^_/.exec(keys[i])
  if (str)
    console.log(keys[i])
}
```

**Comment by hs0225** [comment] 2017-05-10 10:46
@zherczeg I agree that if a user uses the internal object indiscreetly, it causes a problem in the program. But this is not an easy problem to remove it. Especially, modules with native dependency are not easy to fix. Is there a good idea to solve this problem?

@LaszloLango I think  `_onNextTick` and `_onUncaughtException` should be hidden.

**Comment by zherczeg** [comment] 2017-05-10 10:54
I have a simple solution. Currently JS callbacks do something like this:

    JHANDLER_CHECK_THIS(object);
    const iotjs_jval_t* builtin = JHANDLER_GET_THIS(object);

The `JHANDLER_GET_THIS` do no checks. However with IOTJS_DEFINE_NATIVE_HANDLE_INFO, we could easily validate the type of an object. I would propose something:

    IOTJS_DEFINE_NATIVE_HANDLE_INFO(type);

    JHANDLER_THIS_TO_OBJ(builtin, object, type);

The `JHANDLER_THIS_TO_OBJ` would check if `object` is object and its type matches to `type`. If not it returns with error. Otherwise it defines `builtin` as `const iotjs_jval_t*` and stores the internal pointer there (no need another `JHANDLER_GET_THIS` call).

**Comment by yichoi** [comment] 2017-05-11 08:36
#829 can solve a part of problem, GPIO.

**Comment by hs0225** [comment] 2017-05-11 08:45
@zherczeg The best way is to hide the internal object. In the case of `Buffer`, we should consider how to hide internal object like node.js. 
In the sample above, if user change `this` by mistake or intention and call the internal function, I think your solution has a meaning.

**Comment by kolipka** [comment] 2017-05-16 08:16
@hs0225 If I understand correctly nodejs code, they use internal V8 Uint8Array as a prototype for Buffer. It hides internals in native part. (https://github.com/nodejs/node/blob/master/lib/buffer.js#L32) That would require us having similar type from JerryScript or at least in native part of IoT.js

GPIO solution is OK, but it comes at a cost:  gpioPinOpen on each call create new GpioPin class that will occupy memory. In addition such classes GpioPin.prototype will not be equal. If user want's to add own custom helper will have to do it to each instance.

**Comment by daeyeon** [comment] 2017-06-08 05:43
@zherczeg please check #911 made according to your suggestion. I applied it only to Buffer.compare first.

**Comment by daeyeon** [comment] 2017-06-28 12:16
All patches for this seem landed.

**Closed by daeyeon** 2017-06-28 12:16 UTC
Labels: bug
