### ISSUE TITLE
 error: 'struct addrinfo' has no member named 'ai_addr'

### ISSUE THREAD

**Issue by chaolaipi** [Samsung/iotjs#280] opened 2015-11-02 07:15 UTC
i build with command  ./tools/build.py --buildtype=release --target-arch=arm --target-os=nuttx --nuttx-home=/home/wenchao/harmony/nuttx/nuttx --no-checktest --no-init-submodule

and i get this error.

/home/wenchao/harmony/iotjs/src/iotjs_module_dns.cpp: In function 'void iotjs::AfterGetAddrInfo(uv_getaddrinfo_t*, int, addrinfo*)':
/home/wenchao/harmony/iotjs/src/iotjs_module_dns.cpp:42:16: error: 'struct addrinfo' has no member named 'ai_addr'
           res->ai_addr);
                ^
/home/wenchao/harmony/iotjs/src/iotjs_module_dns.cpp:46:16: error: 'struct addrinfo' has no member named 'ai_addr'
           res->ai_addr);
                ^
/home/wenchao/harmony/iotjs/src/iotjs_module_dns.cpp: In function 'iotjs::JObject* iotjs::InitDns()':
/home/wenchao/harmony/iotjs/src/iotjs_module_dns.cpp:123:52: error: 'AI_ADDRCONFIG' was not declared in this scope
     dns->SetProperty("AI_ADDRCONFIG", JVal::Number(AI_ADDRCONFIG));
                                                    ^
/home/wenchao/harmony/iotjs/src/iotjs_module_dns.cpp:124:50: error: 'AI_V4MAPPED' was not declared in this scope
     dns->SetProperty("AI_V4MAPPED", JVal::Number(AI_V4MAPPED));
                                                  ^
make[2]: *** [CMakeFiles/libiotjs.dir/src/iotjs_module_dns.cpp.obj] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/libiotjs.dir/all] Error 2
make: *** [all] Error 2

**Comment by seanshpark** [comment] 2015-11-02 07:20
@chaolaipi , please use `--tuv` option for the moment.

Time to change to `tuv` for default? Or we can add dummy `struct addrinfo` to old nuttx patch.

**Comment by chaolaipi** [comment] 2015-11-02 07:24
@seanshpark ok, thank you

**Comment by yichoi** [comment] 2016-10-07 03:28
Closing since this issue is not reproduced at latest codes.

**Closed by yichoi** 2016-10-07 03:28 UTC
