### ISSUE TITLE
Nuttx on master does not build

### ISSUE THREAD

**Issue by tadziopazur** [Samsung/iotjs#641] opened 2017-02-20 14:49 UTC
As of: 9b68d22867c3028149826fb8a882c68ea3d7b867

The script happily goes thru the failure, as build_nuttx() return value is ignored.
As a side note: setup_nuttx_root() also returns False, but the return value is (also) ignored.

$ rm -rf build/
$ tools/precommit.py --test=nuttx
(...)
cp /opt/iotjs/iotjs.git/build/arm-nuttx/release/lib/lib* .
cp: cannot stat '/opt/iotjs/iotjs.git/build/arm-nuttx/release/lib/lib*': No such file or directory
Makefile:141: recipe for target 'copylibs' failed
make[2]: *** [copylibs] Error 1
make[2]: Leaving directory '/opt/iotjs/iotjs.git/deps/nuttx/apps/system/iotjs'
Makefile:92: recipe for target 'system/iotjs_all' failed
make[1]: *** [system/iotjs_all] Error 2
make[1]: Leaving directory '/opt/iotjs/iotjs.git/deps/nuttx/apps'
LibTargets.mk:174: recipe for target '../apps/libapps.a' failed
make: *** [../apps/libapps.a] Error 2
Failed to build nuttx
(...)

**Comment by Felipeasg** [comment] 2017-02-20 16:15
I also have this failure following the instruncions [here](https://github.com/Samsung/iotjs/blob/master/targets/nuttx-stm32f4/README.md) and [here](https://github.com/Samsung/iotjs/blob/master/docs/build/Build-for-NuttX.md).

But this seems like missing libapps.a due the app in **./nuttx/apps/system/iotjs** that is copied from directory **./iotjs/targets/nuttx-stm32f4/app/***.

To fix this problem and generate the nuttx headers needed to compile **iotjs** I Disable **Application Configuration -> System Libraries and NSH Add-ons -> IoT.js** using the menuconfig on nuttx folder. 

Nuttx finish the compilation without errors but without IoT.js application. But when I try to compile iotjs using the command:

`
./tools/build.py --target-arch=arm --target-os=nuttx --nuttx-home=../nuttx --target-board=stm32f4dis --jerry-heaplimit=78

`

I got the following errors:

```
/home/fadriano/opensource/IoT/iotjs-nuttx/iot-nuttx/iotjs/deps/libtuv/src/unix/fs.c: In function 'uv__to_stat':
/home/fadriano/opensource/IoT/iotjs-nuttx/iot-nuttx/iotjs/deps/libtuv/src/unix/fs.c:553:28: error: 'struct stat' has no member named 'st_atim'
   dst->st_atim.tv_sec = src->st_atim.tv_sec;
                            ^
/home/fadriano/opensource/IoT/iotjs-nuttx/iot-nuttx/iotjs/deps/libtuv/src/unix/fs.c:554:29: error: 'struct stat' has no member named 'st_atim'
   dst->st_atim.tv_nsec = src->st_atim.tv_nsec;
                             ^
/home/fadriano/opensource/IoT/iotjs-nuttx/iot-nuttx/iotjs/deps/libtuv/src/unix/fs.c:555:28: error: 'struct stat' has no member named 'st_mtim'
   dst->st_mtim.tv_sec = src->st_mtim.tv_sec;
                            ^
/home/fadriano/opensource/IoT/iotjs-nuttx/iot-nuttx/iotjs/deps/libtuv/src/unix/fs.c:556:29: error: 'struct stat' has no member named 'st_mtim'
   dst->st_mtim.tv_nsec = src->st_mtim.tv_nsec;
                             ^
/home/fadriano/opensource/IoT/iotjs-nuttx/iot-nuttx/iotjs/deps/libtuv/src/unix/fs.c:557:28: error: 'struct stat' has no member named 'st_ctim'
   dst->st_ctim.tv_sec = src->st_ctim.tv_sec;
                            ^
/home/fadriano/opensource/IoT/iotjs-nuttx/iot-nuttx/iotjs/deps/libtuv/src/unix/fs.c:558:29: error: 'struct stat' has no member named 'st_ctim'
   dst->st_ctim.tv_nsec = src->st_ctim.tv_nsec;
                             ^
/home/fadriano/opensource/IoT/iotjs-nuttx/iot-nuttx/iotjs/deps/libtuv/src/unix/fs.c:568:32: error: 'struct stat' has no member named 'st_ctim'
   dst->st_birthtim.tv_sec = src->st_ctim.tv_sec;
                                ^
/home/fadriano/opensource/IoT/iotjs-nuttx/iot-nuttx/iotjs/deps/libtuv/src/unix/fs.c:569:33: error: 'struct stat' has no member named 'st_ctim'
   dst->st_birthtim.tv_nsec = src->st_ctim.tv_nsec;
                                 ^
CMakeFiles/tuv.dir/build.make:192: recipe for target 'CMakeFiles/tuv.dir/src/unix/fs.c.obj' failed
make[2]: *** [CMakeFiles/tuv.dir/src/unix/fs.c.obj] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/fadriano/opensource/IoT/iotjs-nuttx/iot-nuttx/iotjs/build/arm-nuttx/debug/deps/libtuv'
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/tuv.dir/all' failed
make[1]: *** [CMakeFiles/tuv.dir/all] Error 2
make[1]: Leaving directory '/home/fadriano/opensource/IoT/iotjs-nuttx/iot-nuttx/iotjs/build/arm-nuttx/debug/deps/libtuv'
Makefile:76: recipe for target 'all' failed
make: *** [all] Error 2
make: Leaving directory '/home/fadriano/opensource/IoT/iotjs-nuttx/iot-nuttx/iotjs/build/arm-nuttx/debug/deps/libtuv'
```

This seems to be a problem with **libtub** in file **fs.c**.

**Comment by Felipeasg** [comment] 2017-02-20 17:59
I was able to advance a little.

Knowing that the problem was on the line 553..559 of file **iotjs/deps/libtuv/src/unix/fs.c** I decided to check how nuttx define the **stat struct** on file  _**include/sys/stat.h**_. So I found the following

```
struct stat
{
  /* Required, standard fields */

  mode_t    st_mode;    /* File type, atributes, and access mode bits */
  off_t     st_size;    /* Size of file/directory, in bytes */
  blksize_t st_blksize; /* Blocksize used for filesystem I/O */
  blkcnt_t  st_blocks;  /* Number of blocks allocated */
  time_t    st_atime;   /* Time of last access */
  time_t    st_mtime;   /* Time of last modification */
  time_t    st_ctime;   /* Time of last status change */

  /* Internal fields.  These are part this specific implementation and
   * should not referenced by application code for portability reasons.
   */

#ifdef CONFIG_PSEUDOFS_SOFTLINKS
  uint8_t   st_count;   /* Used internally to limit traversal of links */
#endif
};
```

If you got to line 553 of file **iotjs/deps/libtuv/src/unix/fs.c** You will find the following (when you compile to nuttx):

```
#elif !defined(_AIX) && (       \
    defined(_GNU_SOURCE)     || \
    defined(_BSD_SOURCE)     || \
    defined(_SVID_SOURCE)    || \
    defined(_XOPEN_SOURCE)   || \
    defined(_DEFAULT_SOURCE))
  dst->st_atim.tv_sec = src->**st_atim**.tv_sec;
  dst->st_atim.tv_nsec = src->**st_atim**.tv_nsec;
  dst->st_mtim.tv_sec = src->**st_mtim**.tv_sec;
  dst->st_mtim.tv_nsec = src->**st_mtim**.tv_nsec;
  dst->st_ctim.tv_sec = src->**st_ctim**.tv_sec;
  dst->st_ctim.tv_nsec = src->**st_ctim**.tv_nsec;

```

Then I comment the lines 553 to 558 and the lines 568 and 569. After I execute the command:

```
./tools/build.py --target-arch=arm --target-os=nuttx --nuttx-home=../nuttx --target-board=stm32f4dis --jerry-heaplimit=78

```

And **IoT.js Build succeeded!!!**

After I go to nuttx folder and Enable **Application Configuration -> System Libraries and NSH Add-ons -> IoT.js** 

The make generate the nuttx.bin and nuttx.hex to write on microcontroller... BUT something is wrong with the file fs.c of libtuv. I will try to fix this.

Att.

Felipe Adriano

**Comment by Felipeasg** [comment] 2017-02-20 23:15
I fix this problems. The code could not access the tv_sec and tv_nsec directly, because they are **Internal Fields**, them you need to use **itimerspec struct** to get the stat time.

I change the lines 553 to 558 of file iotjs/deps/libtuv/src/unix/fs.c by the following:

```
#elif !defined(_AIX) && (       \
    defined(_GNU_SOURCE)     || \
    defined(_BSD_SOURCE)     || \
    defined(_SVID_SOURCE)    || \
    defined(_XOPEN_SOURCE)   || \
    defined(_DEFAULT_SOURCE))
  struct itimerspec timerValues_atime, timerValues_mtime, timerValues_ctime;

  timer_settime (src->st_atime, 0, &timerValues_atime, NULL);
  timer_settime (src->st_mtime, 0, &timerValues_mtime, NULL);
  timer_settime (src->st_ctime, 0, &timerValues_ctime, NULL);

  dst->st_atim.tv_sec = timerValues_atime.it_value.tv_sec;
  dst->st_atim.tv_nsec = timerValues_atime.it_value.tv_nsec;
  dst->st_mtim.tv_sec = timerValues_mtime.it_value.tv_sec;
  dst->st_mtim.tv_nsec = timerValues_mtime.it_value.tv_nsec;
  dst->st_ctim.tv_sec = timerValues_ctime.it_value.tv_sec;
  dst->st_ctim.tv_nsec = timerValues_ctime.it_value.tv_nsec;
```

and the line 568 and 569 to the following code:

```
  dst->st_birthtim.tv_sec = timerValues_ctime.it_value.tv_sec;
  dst->st_birthtim.tv_nsec = timerValues_ctime.it_value.tv_nsec;
```

after that go to nuttx folder and copy the .config of iotjs (like this instructions [here](https://github.com/Samsung/iotjs/blob/master/targets/nuttx-stm32f4/README.md))

```
$ cd nuttx
$ cp ../iotjs/targets/nuttx-stm32f4/nuttx/.config.default .config
```

type make menuconfig and Disable **Application Configuration -> System Libraries and NSH Add-ons -> IoT.js**, this is needed in first time to generate some Nuttx files to compile IoT.js. 

Now you can compile IoT.js.

```
$ cd iotjs
$ ./tools/build.py --target-arch=arm --target-os=nuttx --nuttx-home=../nuttx --target-board=stm32f4dis --jerry-heaplimit=78
```

Go to nuttx folder again and enable IoTjs application on make menuconfig and type make. Now the makefile will generate nuttx.hex and .bin.

**Comment by glistening** [comment] 2017-02-21 01:07
The following flags are not related to nuttx.
```
#elif !defined(_AIX) && (       \
    defined(_GNU_SOURCE)     || \
    defined(_BSD_SOURCE)     || \
    defined(_SVID_SOURCE)    || \
    defined(_XOPEN_SOURCE)   || \
    defined(_DEFAULT_SOURCE))
  dst->st_atim.tv_sec = src->st_atim.tv_sec;
  dst->st_atim.tv_nsec = src->st_atim.tv_nsec;
  dst->st_mtim.tv_sec = src->st_mtim.tv_sec;
  dst->st_mtim.tv_nsec = src->st_mtim.tv_nsec;
  dst->st_ctim.tv_sec = src->st_ctim.tv_sec;
  dst->st_ctim.tv_nsec = src->st_ctim.tv_nsec;
# if defined(__DragonFly__)  || \
     defined(__FreeBSD__)    || \
     defined(__OpenBSD__)    || \
     defined(__NetBSD__)
  dst->st_birthtim.tv_sec = src->st_birthtim.tv_sec;
  dst->st_birthtim.tv_nsec = src->st_birthtim.tv_nsec;
  dst->st_flags = src->st_flags;
  dst->st_gen = src->st_gen;
```

For nuttx, the compilation was intended to use the code in the last #else 
```
#else
  dst->st_atim.tv_sec = src->st_atime;
  dst->st_atim.tv_nsec = 0;
  dst->st_mtim.tv_sec = src->st_mtime;
  dst->st_mtim.tv_nsec = 0;
  dst->st_ctim.tv_sec = src->st_ctime;
  dst->st_ctim.tv_nsec = 0;
  dst->st_birthtim.tv_sec = src->st_ctime;
  dst->st_birthtim.tv_nsec = 0;
  dst->st_flags = 0;
  dst->st_gen = 0;
#endif
```
We must find out why the compilation is trying to include the code.
We will check it further.

On my build system, when I build with following commit from 31st, Jan, I have no problem building nuttx.

24b30f1 2017-01-31 Add BLE js and implements bindRaw, emit('data')

**Comment by Felipeasg** [comment] 2017-02-22 01:45
I noticed that.. some flag may be wrong defined on build process, but is the correct way to passa the tv_sec and nv_sec information from stat? couldn't be better use the itimerspec?

To solve the problem temporarily, I remove the code defined by others flags and left only the last #else  as you mentioned above, but accessing throuth itimerspec.

Thanks by the response.

Att.

Felipe

**Comment by hs0225** [comment] 2017-02-24 04:38
@Felipeasg I also have no problem building nuttx. Can I know which of following flags is on?
```
    defined(_GNU_SOURCE)     || \
    defined(_BSD_SOURCE)     || \
    defined(_SVID_SOURCE)    || \
    defined(_XOPEN_SOURCE)   || \
    defined(_DEFAULT_SOURCE))
```
I think, I would rather define `nuttx` explicitly like other platforms.
```
#elif defined(__NUTTX__)
```

**Comment by Felipeasg** [comment] 2017-02-26 14:12
Sorry by the delay.

I checked the file **build.config** on iotjs folder and I saw de definition  "-D__NUTTX__" in "compiler_flags" field.

```
 "compile_flags": {                                                                                          
    "os": {                                                                                                   
      "linux": ["-fno-builtin"],                                                                              
      "darwin": ["-fno-builtin"],                                                                             
      "nuttx": ["-D__NUTTX__",                                                                                
                "-Os",                                                                                        
                "-fno-strict-aliasing",                                                                       
                "-fno-strength-reduce",                                                                       
                "-fomit-frame-pointer"]                                                                       
    }, 
```
But using some **#pragma message** I discovered that the flag defined detected in **./dev/libtuv/src/unix/fs.c**  is  **"_DEFAULT_SOURCE"**.

Thanks again.

Att.

Felipe

**Comment by hs0225** [comment] 2017-03-22 02:02
@Felipeasg @tadziopazur Can not build Nuttx with the latest commit?

**Comment by hs0225** [comment] 2017-03-28 06:59
Closing.
I confirmed that the nuttx build works well in #680. If you have problems, please reopen it again.

**Closed by hs0225** 2017-03-28 06:59 UTC
