### ISSUE TITLE
nuttx minicom /dev/ttyACM0 failed

### ISSUE THREAD

**Issue by chaolaipi** [Samsung/iotjs#278] opened 2015-10-30 07:21 UTC
with stm32f4discovery board, i cannot use minicom to connect to nsh.

my test host is ubuntu14.04. in the /dev directory, there is no file named ttyACM0.  

did i miss any build configuration or else?

**Comment by wateret** [comment] 2015-10-30 07:27
Did you connect micro usb cable?
Writing the image to the board would be enough with mini cable, but you need a micro cable for minicom.

**Comment by chaolaipi** [comment] 2015-10-30 07:35
I have connected micro usb to my host.

**Comment by chunseoklee** [comment] 2015-10-30 07:53
@chaolaipi Did you follow the instruction in https://bitbucket.org/seanshpark/nuttx/wiki/Home ?

**Comment by ILyoan** [comment] 2015-10-31 19:02
We want to help you with the problem but we need more information to figure out what's going on.

With only given information, I'd list couple of suspicious reasons perhaps lead the problem.

* nuttx configuration might not match your actual system. 
* Our configuration assumes there is BB extension to enable networking. If you don't have extension nuttx would failed to boot.
* USB port of your board might broken.

Some part of our document is out of date. we will update it as soon as possible.

**Comment by seanshpark** [comment] 2015-11-01 23:59
@chaolaipi , I've updated [Build for NuttX](https://github.com/Samsung/iotjs/wiki/Build-for-NuttX) page about USB connection but maybe late for you. Hope you find the problem.

**Comment by chaolaipi** [comment] 2015-11-02 03:05
thank you for @seanshpark @ILyoan , i only have a stm32f4-discovery, and without BB extension. I will get a BB extension and go on ...

**Comment by chaolaipi** [comment] 2015-11-02 03:07
@chunseoklee  I have followed the instruction on  your page.

**Comment by yichoi** [comment] 2016-10-07 03:24
Closing since it looks like rare case and hard to find my envinroment. @chaolaipi please let us know if this problem reproduced again.

**Closed by yichoi** 2016-10-07 03:24 UTC
